---
title: "Kmeans"
output: html_document
---

```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(caret, data.table, ggplot2, ranger)
```

## load the data for a few seconds


```{r}
columns <- read.table(
    "./data/kddcup.names",
    sep=":",
    skip=1,  # the first column name are the labels, but those are at the end!
    as.is=T
)
column_names <- c(columns[,1], 'label')

connection_events <- read.csv(
    "./data/kddcup.data_10_percent.gz",
    col.names=column_names
)

setDT(connection_events)  # convert from data.frame to data.table
```

## select the data from connection_events

Try to use kmeans
1. learn how to select columns except the label

```{r}
connection_events$protocol_type <- as.integer(factor(connection_events$protocol_type))
connection_events$service <- as.integer(factor(connection_events$service))
connection_events$flag <- as.integer(factor(connection_events$flag))
kmeansdata <- connection_events[,1:41]
```

## Try kmeans 4 classifications


```{r kmeans, echo=FALSE}
set.seed(20)
irisCluster <- kmeans(kmeansdata, 4, nstart = 20)
```

irisCluster returns cluster, centers, totss and so on.

## add new feature: is_kmeans_1, is_kmeans_2, is_kmeans_3, is_kmeans_4


```{r}
connection_events$is_kmeans_1 <- as.integer(irisCluster$`cluster`==1)
connection_events$is_kmeans_2 <- as.integer(irisCluster$`cluster`==2)
connection_events$is_kmeans_3 <- as.integer(irisCluster$`cluster`==3)
connection_events$is_kmeans_4 <- as.integer(irisCluster$`cluster`==4)
connection_events
```
# connection_events now has the 42+4 features
